### ISSUE TITLE
Chrome Store entry is broken

### ISSUE THREAD

**Issue by arcs-** [null-dev/ChromeSkype#8]
The [Chrome Store entry](https://chrome.google.com/webstore/detail/chromeskype/oghlgehncgibpgmdcblhkbgggeflacnd) is broken. Opening the link or searching for it doesn't reveal the app.

**Comment by null-dev** [comment]
Yeah, it got banned (perhaps because it has the word "Chrome" in the name).

Maybe I will change the name later but for now, I can't do anything about
it.
